apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trivy.fullname" . }}
  labels:
    {{- include "trivy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "trivy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "trivy.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "trivy.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: cache
              mountPath: /tmp/trivy
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: {{ include "trivy.fullname" . }}-cache
