FROM golang:1.22-alpine3.19 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w -X github.com/aquasecurity/trivy/pkg/version.Version=canary" -o trivy ./cmd/trivy

FROM alpine:3.19
RUN apk --no-cache add ca-certificates
COPY --from=builder /app/trivy /usr/local/bin/trivy
ENTRYPOINT ["trivy"]
